coverage:
  status:
    project:
      default:
        target: 70
        threshold: 1
        base: auto
    patch:
      default:
        target: 70
        threshold: 1
    changes:
      default:
        target: 70
        threshold: 1

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
